[package]
name = "libsm64"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsm64-sys = {path = "./libsm64-sys" }
sha = "1.0.3"
